version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    networks:
      - ecommerce_net

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_ecommerce:/var/lib/postgresql/data
    networks:
      - ecommerce_net
    
volumes:
  db_ecommerce:

networks:
  ecommerce_net: